SELECT
    PRODUCTID
    ,  PRODUCTNAME
    ,  CATEGORY
    ,  SUBCATEGORY
    ,  SUM(ORDER_PROFIT) AS PROFIT
FROM
    {{ ref('STAGE_ORDERS') }}

GROUP BY
    PRODUCTID
    ,  PRODUCTNAME
    ,  CATEGORY
    ,  SUBCATEGORY